#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import tensorflow as tf

# 创建一个变量, 初始化为标量 0.
state = tf.Variable(0., name="counter")

# 创建一个 op, 其作用是使 state 增加 1

one = tf.constant(1.)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)
# log = tf.log(state)

# 启动图后, 变量必须先经过`初始化` (init) op 初始化,
# 首先必须增加一个`初始化` op 到图中.
init_op = tf.initialize_all_variables()

# 启动图, 运行 op
# 新建session with log_device_placement并设置为True.
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
  tf.device("/gpu:0")

  # 运行 'init' op
  sess.run(init_op)
  # 打印 'state' 的初始值
  print 'init value:',sess.run(state)
  # 运行 op, 更新 'state', 并打印 'state'
  for _ in range(10):
    sess.run(update)
    print sess.run(state) #,sess.run(log)